on:
  push:
    branches:
      - 'master'

name: deploy

jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE
      - uses: actions/checkout@master
      - name: build a push to docker
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: user/app:latest
          secrets: |
            "username=${{ secrets.DOCKER_USERNAME }}"
            "password=${{ secrets.DOCKERHUB_TOKEN }}"
            "repository=${{ github.repository }}"
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}