on:
  push:
    branches:
      - 'master'

name: deploy

jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: Save state
      run: echo "{name}={value}" >> $GITHUB_STATE
    - uses: actions/checkout@master
    # - name: build a push to docker
    #   uses: docker/build-push-action@v2
    #   with:
    #     build-args:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
    #       repository: ${{ github.repository }}
    #       tags: user/app:latest
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        build-args:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}